// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhv9VhFwLDZMKIp-D2wjxAuuerqApLR6g',
    appId: '1:578546980473:web:7a550ac6ae336b25e366a8',
    messagingSenderId: '578546980473',
    projectId: 'smartfinance-1dc0a',
    authDomain: 'smartfinance-1dc0a.firebaseapp.com',
    storageBucket: 'smartfinance-1dc0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEHSE8LpSiGNAit9d_qynp61lWwQxYdEY',
    appId: '1:578546980473:android:78ec235825c4560ee366a8',
    messagingSenderId: '578546980473',
    projectId: 'smartfinance-1dc0a',
    storageBucket: 'smartfinance-1dc0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuyWY1FAeRdQDDSK7r2BLbKXJENgNAj_Y',
    appId: '1:578546980473:ios:eb107da83800de8be366a8',
    messagingSenderId: '578546980473',
    projectId: 'smartfinance-1dc0a',
    storageBucket: 'smartfinance-1dc0a.firebasestorage.app',
    iosClientId: '578546980473-uts19im73er3dbgife72ffihp9bo4473.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuyWY1FAeRdQDDSK7r2BLbKXJENgNAj_Y',
    appId: '1:578546980473:ios:eb107da83800de8be366a8',
    messagingSenderId: '578546980473',
    projectId: 'smartfinance-1dc0a',
    storageBucket: 'smartfinance-1dc0a.firebasestorage.app',
    iosClientId: '578546980473-uts19im73er3dbgife72ffihp9bo4473.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartfinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhv9VhFwLDZMKIp-D2wjxAuuerqApLR6g',
    appId: '1:578546980473:web:34fe754fd0568011e366a8',
    messagingSenderId: '578546980473',
    projectId: 'smartfinance-1dc0a',
    authDomain: 'smartfinance-1dc0a.firebaseapp.com',
    storageBucket: 'smartfinance-1dc0a.firebasestorage.app',
  );
}
